language: scala

jdk:
  - oraclejdk8

script:
  - sbt plugin/compile plugin/publishLocal
  - sbt ++2.10.6    core/compile core/publishLocal
  - sbt ++2.11.7    core/compile core/publishLocal
  - sbt ++2.12.0-M4 core/compile core/publishLocal scripted
  - sbt ++2.12.0-M5 core/compile core/publishLocal

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/230c239c3e16a2bf85f2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


