sudo: false
language: scala

jdk:
  - oraclejdk8

scala:
  - 2.10.6
  - 2.12.0-M5
  - 2.12.0-RC1
  - 2.12.0-RC2

matrix:
  include:
    - scala: 2.12.0-M4
      env: TEST_SCRIPTED=1
      jdk: oraclejdk8
    - scala: 2.11.8
      env: TEST_SCRIPTED=1
      jdk: oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION core/compile
  - "if [[ $TEST_SCRIPTED = 1 ]]; then sbt plugin/compile plugin/publishLocal && sbt ++$TRAVIS_SCALA_VERSION core/publishLocal scripted; fi"

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/230c239c3e16a2bf85f2
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
